# Build and deploy the documentation.
#
# This workflow assumes the repo is configured to serve Pages from a
# custom Action, and that it has a protected github-pages environment.
on: workflow_dispatch
concurrency:
  group: pages
  cancel-in-progress: false
env:
  FORCE_COLOR: true
  PIP_NO_INPUT: true
  PIP_QUIET: true
  PIP_DISABLE_PIP_VERSION_CHECK: true
permissions: {}  # Explicitly set permissions on each job.
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo.
        uses: actions/checkout@v4
      - name: Install Python.
        uses: actions/setup-python@v5
        with:
          python-version-file: .default-python-version
      - name: Build the documentation.
        run: |
          python -Im pip install .[ci]
          python -Im nox \
            --non-interactive \
            --session docs
      - name: Upload the GitHub Pages artifact.
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html/
          retention-days: 60
  deploy:
    needs: build
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the GitHub Pages site.
        uses: actions/deploy-pages@v4
